
CREATE TABLE DISTRIBUTORS
(
  DISTRIB_ID  NUMBER(18)                        NOT NULL,
  EVENT_ID    NUMBER(18)                        NOT NULL,
  USER_ID     NUMBER(10)                        NOT NULL
);

COMMENT ON COLUMN DISTRIBUTORS.USER_ID IS 'Един или повече разпространители на билети на събитие';

ALTER TABLE DISTRIBUTORS ADD (CONSTRAINT DISTRIB_ID_PK PRIMARY KEY (DISTRIB_ID));
ALTER TABLE DISTRIBUTORS ADD (CONSTRAINT DISTRIBUTORS_EVENT_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID));
ALTER TABLE DISTRIBUTORS ADD (CONSTRAINT DISTRIBUTORS_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID));

CREATE INDEX DISTRIBUTORS_EVENT_ID_INX ON DISTRIBUTORS(EVENT_ID);
CREATE INDEX DISTRIBUTORS_USER_ID_INX ON DISTRIBUTORS(USER_ID);

CREATE SEQUENCE DISTRIBUTORS_DISTRIB_ID_SЕQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
NOORDER;
