
CREATE TABLE SEATS
(
  SEATS_ID          NUMBER(18)                  NOT NULL,
  EVENT_ID          NUMBER(18)                  NOT NULL,
  SEATS_TYPE        VARCHAR2(20 CHAR)           NOT NULL,
  NUMBER_OF_SEATS   NUMBER(8)                   NOT NULL,
  PRICE             NUMBER(6)                   NOT NULL,
  RESERVED_SEATS    NUMBER(8)                   NOT NULL,
  AGE_RESTRICTION   VARCHAR2(20 CHAR)           NOT NULL,
  PURCHASING_LIMIT  NUMBER(4)                   NOT NULL
);

COMMENT ON COLUMN SEATS.SEATS_TYPE IS 'Вид на местата';
COMMENT ON COLUMN SEATS.NUMBER_OF_SEATS IS 'Брой на местата от съответния вид';
COMMENT ON COLUMN SEATS.PRICE IS 'Цена';
COMMENT ON COLUMN SEATS.RESERVED_SEATS IS 'Брой на резервираните места';
COMMENT ON COLUMN SEATS.AGE_RESTRICTION IS 'Възрастово ограничение за закупуване на билета';
COMMENT ON COLUMN SEATS.PURCHASING_LIMIT IS 'Максимален брой билети закупени от едно лице';

ALTER TABLE SEATS ADD (CONSTRAINT SEATS_ID_PK PRIMARY KEY (SEATS_ID));
ALTER TABLE SEATS ADD (CONSTRAINT SEATS_EVENT_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID));
CREATE INDEX SEATS_EVENT_ID_INX ON SEATS(EVENT_ID);

CREATE SEQUENCE SEATS_SEATS_ID_SЕQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
NOORDER;
